In [12]:
import pandas as pd
import numpy as np
import os

In [13]:
os.chdir('/mnt/c/Users/User/notebook/jupyterenv/generic-real-estate-consulting-project-18/')

In [14]:
age_SA2 = pd.read_csv("data/raw/population/age_group/SA2_AGE_POP_csv.csv")
age_LGA = pd.read_csv("data/raw/population/age_group/LGA_AGE_POP_csv.csv")

In [16]:
age_SA2 = age_SA2[age_SA2['S/T name'] == 'Victoria']
age_SA2

,S/T code,S/T name,GCCSA code,GCCSA name,SA4 code,SA4 name,SA3 code,SA3 name,SA2 code,SA2 name,...,45-49,50-54,55-59,60-64,65-69,70-74,75-79,80-84,85 and over,Total persons
642,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011001,Alfredton,...,1142,974,848,709,666,596,419,253,164,16823
643,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011002,Ballarat,...,818,833,812,822,721,736,526,387,380,12076
644,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011005,Buninyong,...,532,495,452,526,474,398,204,134,85,7232
645,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011006,Delacombe,...,565,530,538,479,428,432,280,175,228,10640
646,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011007,Smythes Creek,...,326,344,312,311,242,186,95,40,31,4213
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1159,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21703,Colac - Corangamite,217031476,Otway,...,264,303,363,422,404,311,182,103,71,3978
1160,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041477,Moyne - East,...,444,477,555,526,475,339,210,153,113,6989
1161,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041478,Moyne - West,...,618,675,735,731,781,671,420,228,252,9963
1162,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041479,Warrnambool - North,...,1374,1435,1444,1404,1245,1150,843,543,504,22462
1163,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041480,Warrnambool - South,...,805,855,838,913,885,760,536,391,540,13292

In [17]:
age_SA2.drop(age_SA2.iloc[:, 0:8], inplace=True, axis=1)

/tmp/ipykernel_233/295930571.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  age_SA2.drop(age_SA2.iloc[:, 0:8], inplace=True, axis=1)

In [18]:
age_SA2

,SA2 code,SA2 name,0-4,5-9,10-14,15-19,20-24,25-29,30-34,35-39,...,45-49,50-54,55-59,60-64,65-69,70-74,75-79,80-84,85 and over,Total persons
642,201011001,Alfredton,1230,1388,1457,1318,1073,972,1153,1276,...,1142,974,848,709,666,596,419,253,164,16823
643,201011002,Ballarat,504,589,713,837,728,677,654,660,...,818,833,812,822,721,736,526,387,380,12076
644,201011005,Buninyong,366,552,614,547,397,270,310,395,...,532,495,452,526,474,398,204,134,85,7232
645,201011006,Delacombe,815,764,720,593,841,1069,915,679,...,565,530,538,479,428,432,280,175,228,10640
646,201011007,Smythes Creek,228,298,378,346,213,147,206,236,...,326,344,312,311,242,186,95,40,31,4213
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1159,217031476,Otway,151,168,200,168,109,157,209,193,...,264,303,363,422,404,311,182,103,71,3978
1160,217041477,Moyne - East,426,470,508,441,330,351,437,355,...,444,477,555,526,475,339,210,153,113,6989
1161,217041478,Moyne - West,516,611,729,588,389,424,506,546,...,618,675,735,731,781,671,420,228,252,9963
1162,217041479,Warrnambool - North,1259,1434,1598,1424,1216,1463,1436,1344,...,1374,1435,1444,1404,1245,1150,843,543,504,22462
1163,217041480,Warrnambool - South,641,695,728,713,673,892,832,803,...,805,855,838,913,885,760,536,391,540,13292