In [45]:
import pandas as pd
import numpy as np
import os

In [46]:
# set main directory
main_directory = os.getcwd().replace('/notebooks','')

In [47]:

age_SA2 = pd.read_csv(main_directory+"/data/raw/population/age_group/SA2_AGE_POP.csv")
age_LGA = pd.read_csv(main_directory+"/data/raw/population/age_group/LGA_AGE_POP.csv")

In [48]:
age_SA2 = age_SA2[age_SA2['S/T name'] == 'Victoria']
age_SA2

,S/T code,S/T name,GCCSA code,GCCSA name,SA4 code,SA4 name,SA3 code,SA3 name,SA2 code,SA2 name,...,2016,2017,2018,2019,2020,2021,No.change2011-2021,%change2011-2021,Area/km2,Population density 2021/km2
642,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011001,Alfredton,...,11852,12639,13520,14408,15472,16823,8371,99.0,52.7,319.2
643,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011002,Ballarat,...,12301,12261,12237,12311,12183,12076,-289,-2.3,12.4,975.5
644,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011005,Buninyong,...,7311,7407,7413,7452,7369,7232,507,7.5,51.6,140.2
645,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011006,Delacombe,...,7195,7617,8174,8876,9736,10640,4802,82.3,34.2,311.5
646,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011007,Smythes Creek,...,3990,4002,4040,4109,4148,4213,394,10.3,104.7,40.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1159,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21703,Colac - Corangamite,217031476,Otway,...,3556,3633,3707,3797,3905,3978,558,16.3,1505.9,2.6
1160,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041477,Moyne - East,...,6709,6714,6741,6790,6873,6989,210,3.1,3275.8,2.1
1161,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041478,Moyne - West,...,9603,9681,9773,9833,9842,9963,939,10.4,2037.8,4.9
1162,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041479,Warrnambool - North,...,21442,21676,21934,22157,22379,22462,2583,13.0,62.4,359.9
1163,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041480,Warrnambool - South,...,13173,13192,13214,13247,13323,13292,151,1.1,120.2,110.6

In [49]:
age_SA2.drop(age_SA2.iloc[:, 0:8], inplace=True, axis=1)

In [50]:
age_SA2

,SA2 code,SA2 name,2001,2002,2003,2004,2005,2006,2007,2008,...,2016,2017,2018,2019,2020,2021,No.change2011-2021,%change2011-2021,Area/km2,Population density 2021/km2
642,201011001,Alfredton,5756,6092,6293,6480,6648,6761,7034,7272,...,11852,12639,13520,14408,15472,16823,8371,99.0,52.7,319.2
643,201011002,Ballarat,11497,11708,12015,12189,12269,12356,12408,12480,...,12301,12261,12237,12311,12183,12076,-289,-2.3,12.4,975.5
644,201011005,Buninyong,5320,5399,5557,5620,5857,6037,6131,6252,...,7311,7407,7413,7452,7369,7232,507,7.5,51.6,140.2
645,201011006,Delacombe,4154,4225,4371,4465,4704,5041,5206,5349,...,7195,7617,8174,8876,9736,10640,4802,82.3,34.2,311.5
646,201011007,Smythes Creek,3317,3378,3411,3473,3508,3542,3594,3658,...,3990,4002,4040,4109,4148,4213,394,10.3,104.7,40.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1159,217031476,Otway,3452,3479,3511,3511,3492,3459,3489,3501,...,3556,3633,3707,3797,3905,3978,558,16.3,1505.9,2.6
1160,217041477,Moyne - East,6718,6704,6676,6643,6638,6652,6606,6631,...,6709,6714,6741,6790,6873,6989,210,3.1,3275.8,2.1
1161,217041478,Moyne - West,8317,8387,8450,8487,8517,8601,8694,8792,...,9603,9681,9773,9833,9842,9963,939,10.4,2037.8,4.9
1162,217041479,Warrnambool - North,17053,17449,17726,17937,18172,18528,18877,19107,...,21442,21676,21934,22157,22379,22462,2583,13.0,62.4,359.9
1163,217041480,Warrnambool - South,12506,12578,12639,12697,12748,12792,12839,12903,...,13173,13192,13214,13247,13323,13292,151,1.1,120.2,110.6