In [1]:
import pandas as pd
import glob
import os
import numpy as np

In [2]:
# set main
main_directory = os.getcwd().strip('notebooks')

In [3]:
# reading in the data

SA2_lookup = pd.read_csv(main_directory+"data/raw/MB_2021_AUST_lookup.csv")
LGA_lookup_2021 = pd.read_csv(main_directory+"data/raw/LGA_2021_AUST_lookup.csv")

/var/folders/jv/q8z94ls52bq_4hrt0x88rlb40000gn/T/ipykernel_434/716792561.py:1: DtypeWarning: Columns (0,4,5,7,9,13) have mixed types. Specify dtype option on import or set low_memory=False.
  SA2_lookup = pd.read_csv(main_directory+"data/raw/MB_2021_AUST_lookup.csv")
/var/folders/jv/q8z94ls52bq_4hrt0x88rlb40000gn/T/ipykernel_434/716792561.py:2: DtypeWarning: Columns (0,1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  LGA_lookup_2021 = pd.read_csv(main_directory+"data/raw/LGA_2021_AUST_lookup.csv")

In [4]:
# filter out so only state of Victoria

SA2_lookup = SA2_lookup[SA2_lookup['STATE_NAME_2021'] == 'Victoria']

,MB_CODE_2021,MB_CATEGORY_2021,CHANGE_FLAG_2021,CHANGE_LABEL_2021,SA1_CODE_2021,SA2_CODE_2021,SA2_NAME_2021,SA3_CODE_2021,SA3_NAME_2021,SA4_CODE_2021,SA4_NAME_2021,GCCSA_CODE_2021,GCCSA_NAME_2021,STATE_CODE_2021,STATE_NAME_2021,AUS_CODE_2021,AUS_NAME_2021,AREA_ALBERS_SQKM,ASGS_LOCI_URI_2021
112738,20000010000,Education,0,No change,20403106914,204031069,Bright - Mount Beauty,20403,Wodonga - Alpine,204,Hume,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,0.0127,http://linked.data.gov.au/dataset/asgsed3/MB/2...
112739,20000021000,Commercial,0,No change,20403106902,204031069,Bright - Mount Beauty,20403,Wodonga - Alpine,204,Hume,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,0.0127,http://linked.data.gov.au/dataset/asgsed3/MB/2...
112740,20000022000,Commercial,0,No change,20403106902,204031069,Bright - Mount Beauty,20403,Wodonga - Alpine,204,Hume,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,0.0105,http://linked.data.gov.au/dataset/asgsed3/MB/2...
112741,20000023000,Commercial,0,No change,20403106902,204031069,Bright - Mount Beauty,20403,Wodonga - Alpine,204,Hume,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,0.0105,http://linked.data.gov.au/dataset/asgsed3/MB/2...
112742,20000031000,Commercial,0,No change,20403106902,204031069,Bright - Mount Beauty,20403,Wodonga - Alpine,204,Hume,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,0.0117,http://linked.data.gov.au/dataset/asgsed3/MB/2...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201472,27000004777,SHIPPING,0,No change,29797979993,297979799,Migratory - Offshore - Shipping (Vic.),29797,Migratory - Offshore - Shipping (Vic.),297,Migratory - Offshore - Shipping (Vic.),29799,Migratory - Offshore - Shipping (Vic.),2,Victoria,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/2...
201473,27000005777,SHIPPING,0,No change,29797979993,297979799,Migratory - Offshore - Shipping (Vic.),29797,Migratory - Offshore - Shipping (Vic.),297,Migratory - Offshore - Shipping (Vic.),29799,Migratory - Offshore - Shipping (Vic.),2,Victoria,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/2...
201474,28000000778,MIGRATORY,0,No change,29797979991,297979799,Migratory - Offshore - Shipping (Vic.),29797,Migratory - Offshore - Shipping (Vic.),297,Migratory - Offshore - Shipping (Vic.),29799,Migratory - Offshore - Shipping (Vic.),2,Victoria,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/2...
201475,29000000779,OFFSHORE,0,No change,29797979992,297979799,Migratory - Offshore - Shipping (Vic.),29797,Migratory - Offshore - Shipping (Vic.),297,Migratory - Offshore - Shipping (Vic.),29799,Migratory - Offshore - Shipping (Vic.),2,Victoria,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/2...
201476,20000009499,NOUSUALRESIDENCE,0,No change,29999949999,299999499,No usual address (Vic.),29999,No usual address (Vic.),299,No usual address (Vic.),29499,No usual address (Vic.),2,Victoria,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/2...

In [5]:
# remove null values

SA2_lookup = SA2_lookup[SA2_lookup.AREA_ALBERS_SQKM.notnull()]

In [7]:
# drop irrelevant columns

dropped_columns = ['MB_CATEGORY_2021', 'SA1_CODE_2021',
                   'SA3_CODE_2021','SA3_NAME_2021', 'SA4_CODE_2021', 'SA4_NAME_2021', 
                   'GCCSA_CODE_2021', 'GCCSA_NAME_2021', 'AUS_CODE_2021', 'AUS_NAME_2021', 
                   'AREA_ALBERS_SQKM', 'ASGS_LOCI_URI_2021', 'CHANGE_FLAG_2021', 'CHANGE_LABEL_2021']
SA2_lookup = SA2_lookup.drop(dropped_columns, axis=1)

In [11]:
# filter out all states that are not Victoria

LGA_lookup_2021 = LGA_lookup_2021[LGA_lookup_2021.STATE_NAME_2021 == 'Victoria']

,MB_CODE_2021,LGA_CODE_2021,LGA_NAME_2021,STATE_CODE_2021,STATE_NAME_2021,AUS_CODE_2021,AUS_NAME_2021,AREA_ALBERS_SQKM,ASGS_LOCI_URI_2021
112738,20688570000,20110,Alpine,2,Victoria,AUS,Australia,4.7260,http://linked.data.gov.au/dataset/asgsed3/MB/2...
112739,20000150000,20110,Alpine,2,Victoria,AUS,Australia,0.0429,http://linked.data.gov.au/dataset/asgsed3/MB/2...
112740,20631921910,20110,Alpine,2,Victoria,AUS,Australia,0.0111,http://linked.data.gov.au/dataset/asgsed3/MB/2...
112741,20000140000,20110,Alpine,2,Victoria,AUS,Australia,0.0362,http://linked.data.gov.au/dataset/asgsed3/MB/2...
112742,20688230000,20110,Alpine,2,Victoria,AUS,Australia,0.0272,http://linked.data.gov.au/dataset/asgsed3/MB/2...
...,...,...,...,...,...,...,...,...,...
201472,29000000779,29799,Migratory - Offshore - Shipping (Vic.),2,Victoria,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/2...
201473,27000005777,29799,Migratory - Offshore - Shipping (Vic.),2,Victoria,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/2...
201474,27000004777,29799,Migratory - Offshore - Shipping (Vic.),2,Victoria,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/2...
201475,27000002777,29799,Migratory - Offshore - Shipping (Vic.),2,Victoria,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/2...
201476,27000003777,29799,Migratory - Offshore - Shipping (Vic.),2,Victoria,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/2...

In [12]:
# remove null values

LGA_LOOKUP_2021 = LGA_lookup_2021[LGA_lookup_2021.AREA_ALBERS_SQKM.notnull()]

In [13]:
# remove the Unincorporated Vic area

LGA_LOOKUP_2021 = LGA_LOOKUP_2021[LGA_LOOKUP_2021.LGA_NAME_2021 != 'Unincorporated Vic']

In [14]:
# remove irrelevant columns

LGA_LOOKUP_2021.drop(LGA_LOOKUP_2021.iloc[:, 3:9], inplace=True, axis=1)

In [16]:
# combine SA2 lookup with LGA lookup
# the SA2 french island is removed
combine_df = pd.merge(SA2_lookup,LGA_LOOKUP_2021,how = 'inner',on='MB_CODE_2021')

In [18]:
# drop duplicate column

combine_df = combine_df.drop_duplicates(subset = ['SA2_CODE_2021'],keep = 'first')

In [19]:
# sort the Values by SA2 code

combine_df.sort_values('SA2_CODE_2021', ascending = True)

,MB_CODE_2021,SA2_CODE_2021,SA2_NAME_2021,STATE_CODE_2021,STATE_NAME_2021,LGA_CODE_2021,LGA_NAME_2021
508,20004360000,201011001,Alfredton,2,Victoria,20570,Ballarat
490,20004170000,201011002,Ballarat,2,Victoria,20570,Ballarat
1321,20012900000,201011005,Buninyong,2,Victoria,20570,Ballarat
574,20005160000,201011006,Delacombe,2,Victoria,20570,Ballarat
20761,20201770000,201011007,Smythes Creek,2,Victoria,22490,Golden Plains
...,...,...,...,...,...,...,...
13797,20134030000,217031476,Otway,2,Victoria,21750,Colac Otway
456,20003933000,217041477,Moyne - East,2,Victoria,25490,Moyne
20459,20199200000,217041478,Moyne - West,2,Victoria,22410,Glenelg
52082,20508721000,217041479,Warrnambool - North,2,Victoria,25490,Moyne
52055,20508482000,217041480,Warrnambool - South,2,Victoria,25490,Moyne

In [20]:
# drop even more irrelevant columns

combine_df = combine_df.drop(['MB_CODE_2021', 'STATE_CODE_2021', 'STATE_NAME_2021'], axis = 1)

In [21]:
# rename the columns for merging

combine_df.rename(columns = {'SA2_CODE_2021' : 'SA2 code',
                            'SA2_NAME_2021' : 'SA2 name',
                            'LGA_CODE_2021' : 'LGA code',
                            'LGA_NAME_2021' : 'LGA name'})

        SA2 code                        SA2 name LGA code      LGA name
0      204031069           Bright - Mount Beauty    20110        Alpine
50     204031075                    Yackandandah    20110        Alpine
86     204031071                      Myrtleford    20110        Alpine
256    215011386                          Ararat    20260        Ararat
269    215011387                Ararat Surrounds    20260        Ararat
...          ...                             ...      ...           ...
78092  211051285                Wandin - Seville    27450  Yarra Ranges
78337  211051276        Healesville - Yarra Glen    27450  Yarra Ranges
78533  211051279                Monbulk - Silvan    27450  Yarra Ranges
79220  206041507  Royal Botanic Gardens Victoria    24600     Melbourne
84474  212031556             Clyde North - South    21610         Casey

[521 rows x 4 columns]

In [22]:
# save the dataframe as a csv

combine_df.to_csv((main_directory+"data/curated/LGA_to_SA2.csv"))