In [34]:
# import packages
import os
import pandas as pd

In [35]:
# set directory
main_directory=os.getcwd().strip('notebooks')

## Generate modelling dataset

In [36]:
# get rental_population df
rental_pop=pd.read_csv(main_directory+'data/curated/population/rental_population.csv')

In [37]:
rental_pop

,Unnamed: 0,cost_text,property_type,SA2 code_x,SA2 name,S/T name,SA2 code_y,pop_2012,pop_2013,pop_2014,pop_2015,pop_2016,pop_2017,pop_2018,pop_2019,pop_2020,pop_2021,Area,pop_density_2021
0,0,460.0,House,201011001,Alfredton,Victoria,201011001,9060,9714,10338,11039,11852,12639,13520,14408,15472,16823,52.7,319.2
1,1,440.0,House,201011001,Alfredton,Victoria,201011001,9060,9714,10338,11039,11852,12639,13520,14408,15472,16823,52.7,319.2
2,2,430.0,House,201011001,Alfredton,Victoria,201011001,9060,9714,10338,11039,11852,12639,13520,14408,15472,16823,52.7,319.2
3,3,460.0,House,201011001,Alfredton,Victoria,201011001,9060,9714,10338,11039,11852,12639,13520,14408,15472,16823,52.7,319.2
4,4,440.0,House,201011001,Alfredton,Victoria,201011001,9060,9714,10338,11039,11852,12639,13520,14408,15472,16823,52.7,319.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6641,6641,600.0,House,217041480,Warrnambool - South,Victoria,217041480,13146,13157,13154,13150,13173,13192,13214,13247,13323,13292,120.2,110.6
6642,6642,212.0,Studio,217041480,Warrnambool - South,Victoria,217041480,13146,13157,13154,13150,13173,13192,13214,13247,13323,13292,120.2,110.6
6643,6643,390.0,House,217041480,Warrnambool - South,Victoria,217041480,13146,13157,13154,13150,13173,13192,13214,13247,13323,13292,120.2,110.6
6644,6644,380.0,House,217041480,Warrnambool - South,Victoria,217041480,13146,13157,13154,13150,13173,13192,13214,13247,13323,13292,120.2,110.6
6645,6645,500.0,House,217041480,Warrnambool - South,Victoria,217041480,13146,13157,13154,13150,13173,13192,13214,13247,13323,13292,120.2,110.6

In [38]:
# get conversion data
conversion = pd.read_csv(main_directory+'data/curated/conversion/LGA_to_SA2.csv')

In [39]:
# get crime data
crime =pd.read_csv(main_directory+'data/curated/crime/crime_ratios_all.csv')

In [40]:
# drop unneeded columns
for i in range(12,21):
    rental_pop.drop(columns = ['pop_20' + str(i)], inplace = True)

In [41]:
rental_pop.drop(columns = ['Unnamed: 0', 'pop_density_2021', 'S/T name','SA2 code_x'], inplace = True)

In [45]:
# get income data - current
current_income = pd.read_csv(main_directory + 'data/curated/income/vic_income_by_sa2.csv')
# only want most recent income - mean and median, whichever one works
current_income_relevant = pd.DataFrame()
current_income_relevant['SA2 NAME']=current_income['SA2 NAME']
current_income_relevant['Median $ 2019'] = current_income['Median $ 2019']
current_income_relevant['Mean $ 2019'] = current_income['Mean $ 2019']

In [46]:
# get current crime data
current_crime = pd.DataFrame()
current_crime['LGA code'] = crime['LGA code']
current_crime['2021']= crime['2021']

In [47]:
# get population data
population = pd.read_csv(main_directory+'data/curated/population/by age/SA2_Vic_age_clean.csv')

In [48]:
# rename columns so its identifiable
population = population.add_suffix('_population')

In [49]:
# merge population and rental
merge_pop_rent = rental_pop.merge(population,how = 'left', left_on = ['SA2 name'], right_on=['SA2 name_population'])

In [50]:
# drop unnecessary columns
merge_pop_rent.drop(columns = ['Unnamed: 0_population', 'SA2 code_y'], inplace = True)

In [51]:
merge_pop_rent

,cost_text,property_type,SA2 name,pop_2021,Area,SA2 code_population,SA2 name_population,Children_population,Early_Working_age_population,Prime_Working_age_population,Mature_Working_age_population,Elderly_population
0,460.0,House,Alfredton,16823,52.7,201011001,Alfredton,4075,2391,7550,1375,18255
1,440.0,House,Alfredton,16823,52.7,201011001,Alfredton,4075,2391,7550,1375,18255
2,430.0,House,Alfredton,16823,52.7,201011001,Alfredton,4075,2391,7550,1375,18255
3,460.0,House,Alfredton,16823,52.7,201011001,Alfredton,4075,2391,7550,1375,18255
4,440.0,House,Alfredton,16823,52.7,201011001,Alfredton,4075,2391,7550,1375,18255
...,...,...,...,...,...,...,...,...,...,...,...,...
6641,600.0,House,Warrnambool - South,13292,120.2,217041480,Warrnambool - South,2064,1386,5817,1798,15519
6642,212.0,Studio,Warrnambool - South,13292,120.2,217041480,Warrnambool - South,2064,1386,5817,1798,15519
6643,390.0,House,Warrnambool - South,13292,120.2,217041480,Warrnambool - South,2064,1386,5817,1798,15519
6644,380.0,House,Warrnambool - South,13292,120.2,217041480,Warrnambool - South,2064,1386,5817,1798,15519
6645,500.0,House,Warrnambool - South,13292,120.2,217041480,Warrnambool - South,2064,1386,5817,1798,15519

In [52]:
# put indexing columns at the front
SA2code = merge_pop_rent['SA2 code_population']
merge_pop_rent.drop(columns = ['SA2 code_population'], inplace = True)
merge_pop_rent.insert(2,'SA2 code',SA2code)

In [53]:
# get the LGAs into the dataset for inputing crime
merge_LGA = merge_pop_rent.merge(conversion, how = 'left', left_on = ['SA2 name'], right_on = ['SA2_NAME_2021'])

In [54]:
# merge crime and the rest of the data
merge_crime_all = merge_LGA.merge(current_crime, how = 'left', left_on = ['LGA_NAME_2021'], right_on = ['LGA code'])

In [55]:
# drop unnecessary columns
merge_crime_all.drop(columns = ['SA2 name_population','Unnamed: 0', 'SA2_CODE_2021', 'SA2_NAME_2021', 'LGA_CODE_2021', 'LGA_NAME_2021'], inplace=True)

In [56]:
merge_crime_all.rename(columns = {"2021": "2021 crime rate"},inplace = True) # rename crime rate col

In [57]:
# put indexing columns at the front
LGAcode = merge_crime_all['LGA code']
merge_crime_all.drop(columns = ['LGA code'], inplace = True)
merge_crime_all.insert(2,'LGA code',LGAcode)

In [1]:
# merge with current income -> completed all non poi merging
merge_all = merge_crime_all.merge(current_income_relevant, how = 'left',left_on = ['SA2 name'], right_on = ['SA2 NAME'])

NameError: name 'merge_crime_all' is not defined

In [59]:
merge_all.drop(columns = ["SA2 NAME"], inplace = True)

In [2]:
adffdasfsdf

NameError: name 'adffdasfsdf' is not defined

In [61]:
# save to csv to be modelled in summary notebook
merge_all.to_csv(main_directory+'data/curated/external_features(SA2).csv')