In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
os.chdir('/mnt/c/Users/User/notebook/jupyterenv/generic-real-estate-consulting-project-18/')

In [3]:
# loads the population data for both SA2 and LGA

pop_SA2 = pd.read_csv("data/raw/population/SA2_Population 2001-2021 partial_cleaned.csv")
pop_LGA = pd.read_csv("data/raw/population/LGA_population 2001-2021 partially cleaned.csv")
LGA_lookup = pd.read_csv("data/raw/population/LGA_2020_VIC.csv")

In [4]:
# filters out the dataframe to only have SA2 in Victoria

pop_SA2_vic = pop_SA2[pop_SA2['S/T name'] == 'Victoria']
pop_SA2_vic

,S/T code,S/T name,GCCSA code,GCCSA name,SA4 code,SA4 name,SA3 code,SA3 name,SA2 code,SA2 name,...,2016,2017,2018,2019,2020,2021,No.change2011-2021,%change2011-2021,Area/km2,Population density 2021/km2
642,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011001,Alfredton,...,11852,12639,13520,14408,15472,16823,8371,99.0,52.7,319.2
643,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011002,Ballarat,...,12301,12261,12237,12311,12183,12076,-289,-2.3,12.4,975.5
644,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011005,Buninyong,...,7311,7407,7413,7452,7369,7232,507,7.5,51.6,140.2
645,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011006,Delacombe,...,7195,7617,8174,8876,9736,10640,4802,82.3,34.2,311.5
646,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011007,Smythes Creek,...,3990,4002,4040,4109,4148,4213,394,10.3,104.7,40.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1159,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21703,Colac - Corangamite,217031476,Otway,...,3556,3633,3707,3797,3905,3978,558,16.3,1505.9,2.6
1160,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041477,Moyne - East,...,6709,6714,6741,6790,6873,6989,210,3.1,3275.8,2.1
1161,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041478,Moyne - West,...,9603,9681,9773,9833,9842,9963,939,10.4,2037.8,4.9
1162,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041479,Warrnambool - North,...,21442,21676,21934,22157,22379,22462,2583,13.0,62.4,359.9
1163,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041480,Warrnambool - South,...,13173,13192,13214,13247,13323,13292,151,1.1,120.2,110.6

In [5]:
# drops the irrelevant columns which are GCCSA,SA3 and SA4

pop_SA2_vic.drop(pop_SA2_vic.iloc[:, 2:8], inplace=True, axis=1)

/tmp/ipykernel_117/2265230103.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pop_SA2_vic.drop(pop_SA2_vic.iloc[:, 2:8], inplace=True, axis=1)

In [6]:
# drops years pre 2012 as we want a 10 year period

pop_SA2_vic.drop(pop_SA2_vic.iloc[:, 4:15], inplace=True, axis=1)

/tmp/ipykernel_117/1564761689.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pop_SA2_vic.drop(pop_SA2_vic.iloc[:, 4:15], inplace=True, axis=1)

In [7]:
# drops the percentage change and number of change from 2011-2021

pop_SA2_vic = pop_SA2_vic.drop(['No.change2011-2021', '%change2011-2021'], axis = 1)

In [8]:
pop_SA2_vic

,S/T code,S/T name,SA2 code,SA2 name,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,Area/km2,Population density 2021/km2
642,2,Victoria,201011001,Alfredton,9060,9714,10338,11039,11852,12639,13520,14408,15472,16823,52.7,319.2
643,2,Victoria,201011002,Ballarat,12357,12352,12327,12300,12301,12261,12237,12311,12183,12076,12.4,975.5
644,2,Victoria,201011005,Buninyong,6854,6984,7082,7191,7311,7407,7413,7452,7369,7232,51.6,140.2
645,2,Victoria,201011006,Delacombe,6020,6267,6583,6846,7195,7617,8174,8876,9736,10640,34.2,311.5
646,2,Victoria,201011007,Smythes Creek,3872,3914,3945,3966,3990,4002,4040,4109,4148,4213,104.7,40.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1159,2,Victoria,217031476,Otway,3456,3497,3519,3538,3556,3633,3707,3797,3905,3978,1505.9,2.6
1160,2,Victoria,217041477,Moyne - East,6764,6749,6734,6716,6709,6714,6741,6790,6873,6989,3275.8,2.1
1161,2,Victoria,217041478,Moyne - West,9167,9300,9383,9467,9603,9681,9773,9833,9842,9963,2037.8,4.9
1162,2,Victoria,217041479,Warrnambool - North,20253,20612,20930,21217,21442,21676,21934,22157,22379,22462,62.4,359.9
1163,2,Victoria,217041480,Warrnambool - South,13146,13157,13154,13150,13173,13192,13214,13247,13323,13292,120.2,110.6

In [9]:
pop_LGA

,LGA code,Local Government Area,2001,2002,2003,2004,2005,2006,2007,2008,...,2018,2019,2020,2021,Unnamed: 23,change2011-2021no.,change2011-2021%,Unnamed: 26,Area(km2),Population density 2021(persons/km2)
0,10050.0,Albury,45265.0,45816.0,46180.0,46505.0,47004.0,47566.0,48140.0,48518.0,...,53857.0,54567.0,55350.0,56036.0,NaN,6585.0,13.3,NaN,305.6,183.3
1,10180.0,Armidale Regional,27906.0,27774.0,27610.0,27410.0,27350.0,27377.0,27468.0,27788.0,...,29604.0,29663.0,29551.0,29332.0,NaN,759.0,2.7,NaN,7809.4,3.8
2,10250.0,Ballina,37856.0,38417.0,38870.0,39120.0,39305.0,39537.0,39824.0,40020.0,...,44333.0,44927.0,45569.0,46172.0,NaN,5425.0,13.3,NaN,485.0,95.2
3,10300.0,Balranald,2751.0,2703.0,2661.0,2596.0,2545.0,2507.0,2473.0,2433.0,...,2305.0,2283.0,2252.0,2207.0,NaN,-146.0,-6.2,NaN,21690.7,0.1
4,10470.0,Bathurst Regional,35504.0,35831.0,36084.0,36245.0,36547.0,36916.0,37272.0,37904.0,...,42834.0,43137.0,43355.0,43653.0,NaN,3693.0,9.2,NaN,3817.9,11.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
546,99399.0,Unincorp. Other Territories,542.0,464.0,441.0,428.0,413.0,386.0,370.0,370.0,...,2296.0,2359.0,2434.0,2530.0,NaN,2141.0,550.4,NaN,105.9,23.9
547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# drops years 2001-2011

pop_LGA.drop(pop_LGA.iloc[:, 2:13], inplace=True, axis=1)

In [11]:
# drops the unnamed columns and the 2011-2021 change columns

pop_LGA.drop(pop_LGA.iloc[:, 12:16], inplace=True, axis=1)

In [12]:
# drops NaN values in the dataframe

pop_LGA = pop_LGA.dropna()

In [13]:
# converts the LGA code column to int for merge

pop_LGA['LGA code'] = pop_LGA['LGA code'].astype('int')

/tmp/ipykernel_117/2712096862.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pop_LGA['LGA code'] = pop_LGA['LGA code'].astype('int')

In [14]:
# drops the irrelevant columns for the LGA lookup dataframe

LGA_lookup = LGA_lookup.drop(['MB_CODE_2016', 'AREA_ALBERS_SQKM'], axis = 1)

In [15]:
# drops duplicates as the dataframe is filled with tons of them

LGA_lookup = LGA_lookup.drop_duplicates()

In [16]:
# drops first and last rows as they dont exist in LGA

LGA_lookup = LGA_lookup.drop(LGA_lookup.index[0])
LGA_lookup = LGA_lookup.drop(LGA_lookup.index[-1])

In [17]:
# renamed column for merging purposes

LGA_lookup.rename(columns = {'LGA_CODE_2020':'LGA code'}, inplace = True)

In [18]:
# merge the LGA lookup with the LGA population column

LGA_full = pd.merge(pop_LGA, LGA_lookup, how="inner", on=["LGA code"])

In [19]:
# drops columns from the LGA lookup as they exist already in the LGA pop column

LGA_full.drop(LGA_full.iloc[:, 14:18], inplace=True, axis=1)

In [20]:
# exports these dataframes into a csv file

LGA_full.to_csv("data/curated/population/LGA_Vic_pop_clean.csv")
pop_SA2_vic.to_csv("data/curated/population/SA2_Vic_pop_clean.csv")